openapi: 3.0.3
info:
  title: Apideck
  version: 0.0.1
servers:
  - url: "https://unify.apideck.com"
externalDocs:
  description: Apideck Developer Docs
  url: "https://developers.apideck.com"
security:
  - apiKey: []
paths:
  /hello:
    $ref: ./src/operations/hello/spec.yml
  /space/rockets/{rocketId}:
    $ref: ./src/services/spaceX/spec.yml
