openapi: 3.0.3
info:
  title: Apideck
  version: 0.0.1
servers:
  - url: "https://unify.apideck.com"
externalDocs:
  description: Apideck Developer Docs
  url: "https://developers.apideck.com"
security:
  - apiKey: []
paths:
  /hello:
    get:
      operationId: hello
      responses:
        "200":
          description: "Say hello"
          content: {}
  /space/rockets/{rocketId}:
    get:
      operationId: rocketsOne
      parameters:
        - name: rocketId
          required: true
          in: path
          schema:
            type: string
            example: 5e9d0d95eda69955f709d1eb
      responses:
        "200":
          description: "Get a rocket"
          content: {}
